#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

xrandr --output HDMI-0 --mode 1920x1080 --rate 75

setxkbmap -layout us,latam -option grp:alt_shift_toggle

xinput set-prop 9 "libinput Accel Profile Enabled" 0 1 0

bspc monitor -d 1 2 3 4 5

bspc config border_width 0
bspc config window_gap 12

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

feh --bg-fill /home/dax/Downloads/adrenaline.png

~/.config/polybar/launch.sh

xsetroot -cursor_name left_ptr &

picom -b --experimental-backends
